HairSalon/Models/Client.cs
using System.ComponentModel;
using System.Collections.Generic;
namespace FavoriteClient.Models
{
  public class Client
  {
    
    
    
    [DisplayName("Client Id")]
    public int ClientId { get; set; }
    [DisplayName("Stylist Id")]
    public int StylistId { get; set; }
    [DisplayName("Client Name:")]
    public string Name { get; set; }
    public string Address { get; set; }
    [DisplayName("Client Phone Number:")]
    public string PhoneNumber { get; set; }
  
   [DisplayName("Stylist:")]
    public virtual Stylist Stylist { get; set; }
  
  
  }
}
  
     
    
     





 

HairSalon/Models/ClientContext.cs
using Microsoft.EntityFrameworkCore;

namespace FavoriteClient.Models
{
  public class FavoriteClientContext : DbContext
  {
    public virtual DbSet<Stylist> Stylists { get; set; }
    public DbSet<Client> Clients { get; set; }
    public FavoriteClientContext(DbContextOptions options) : base(options) { }
  }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace FavoriteClient.Models
{
  public class Stylist
  {
    public Stylist()
    {
      this.Clients = new HashSet<Client>();
      
    }
    public int StylistId { get; set; }

    public string Type { get; set; }

    public virtual ICollection<Client> Clients { get; set; }
  }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FavoriteClient.Models;
using System.Collections.Generic;
using System.Linq;

namespace FavoriteClient.Controllers
{
  public class ClientsController : Controller
  {
    private readonly FavoriteClientContext _db;

    public ClientsController(FavoriteClientContext db)
    {
      _db = db;
    }
    public ActionResult Create()
    {
   
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Type");
     
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Index()
    {
      
      List<Client> model = _db.Clients.Include(clients => clients.Stylist).ToList();
      
      return View(model);
    }
    
    
    public ActionResult Details(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
     
      return View(thisClient);
    }
  }
}
    
   
     
     
      
     
        
    


  

     
   
     
     
      


  

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace FavoriteClient.Controllers
{
  public class HomeController : Controller
  {
      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }
  } 
}
         
   
  
        



        
        
        
        
        
        
        

HairSalon/Controllers/StylistsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FavoriteClient.Models;
using System.Collections.Generic;
using System.Linq;



namespace FavoriteClient.Controllers
{
  public class StylistsController : Controller
  {
    private readonly FavoriteClientContext _db; 
    public StylistsController(FavoriteClientContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.OrderBy(stylist => stylist.Type).ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
   
    {
    Stylist thisStylist = _db.Stylists.Include(stylist => stylist.Clients).FirstOrDefault(stylist =>stylist.StylistId == id);
    
    return View(thisStylist);
    }
  }
}







    

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model FavoriteClient.Models.Client

<h4>Add a new client</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
  <br>
  @Html.LabelFor(model => model.Address)
  @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
  <br>
  @Html.LabelFor(model => model.PhoneNumber)
  @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control" })
  <br>
  @Html.LabelFor(model => model.Stylist)
  @Html.DropDownList("StylistId")
  <br>
  
  <input type="submit" value="Add new client" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all clients", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>




  


  
  

 

HairSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@model FavoriteClient.Models.Client

<h2>Client Details</h2>
<hr>
<h4>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h4>
<h4>@Html.DisplayNameFor(model => model.Address): @Html.DisplayFor(model => model.Address)</h4>
<h4>@Html.DisplayNameFor(model => model.PhoneNumber): @Html.DisplayFor(model => model.PhoneNumber)</h4>
<p>@Html.ActionLink("Show all clients", "Index")</p>
<p>@Html.ActionLink("Add new client", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>
<div> @ViewBag.StylistId </div>











 

   

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using FavoriteClient.Models;
@model List<FavoriteClient.Models.Client>;

<h1>Clients</h1>

@if (@Model.Count == 0 )
{
  <h3>No clients have been added yet!</h3>
  <h3>Please add a stylist first.</h3>
}

@foreach (Client client in Model)
{
 <li>@Html.ActionLink($"{client.Name}", "Details", new { id = client.ClientId }) | @client.Stylist.Type</li>
}
<br> 
<p>@Html.ActionLink("Add new stylist", "Create")</p>
<p>@Html.ActionLink("Add new Client", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p> 

  
  

HairSalon/Views/Home/Index.cshtml
@using FavoriteClient.Models;
@{
  Layout = "_Layout";
}

@model  List<FavoriteClient.Models.Stylist>;

<h1>Welcome To The Salon!</h1>

<p>@Html.ActionLink("See a List of all Stylists", "Index", "Stylists")</p>
<p>@Html.ActionLink("See a List of all Clients", "Index", "Clients")</p>



 

HairSalon/Views/Restaurants/Create.cshtml
@{
  Layout = "_Layout";
}

@model FavoriteRestaurant.Models.Restaurant
@using FavoriteRestaurant.Models

@* @ViewBag.Hello *@
<h4>Add a new restaurant</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
  <br>
  @Html.LabelFor(model => model.PriceRange)
  @Html.TextBoxFor(model => model.PriceRange, new { @class = "form-control" })
  <br>
  @Html.LabelFor(model => model.Takeout)
  @Html.TextBoxFor(model => model.Takeout, new { @class = "form-control" })
  <br>
  @Html.LabelFor(model => model.DineIn)
  @Html.TextBoxFor(model => model.DineIn, new { @class = "form-control" })
  <br>
  @Html.LabelFor(model => model.Address)
  @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
  <br>
  @Html.LabelFor(model => model.PhoneNumber)
  @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control" })
  <br>
  @Html.LabelFor(model => model.PassedHealthInspection)
  @Html.DropDownList("PassedHealthInspection",
                    new SelectList(Enum.GetValues(typeof(Health))),
                    new { @class = "form-control" })
  <br>
  @Html.LabelFor(model => model.Cuisine)
  @Html.DropDownList("CuisineId")
  @* this is connected to the viewbag from the RestaurantController on line 22 *@
  
  
  <input type="submit" value="Add new restaurant" class="btn btn-default" />
}

<p>@Html.ActionLink("Show all restaurants", "Index")</p>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Favorite Clients</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <div class="container">
      @RenderBody()
      <footer>
        <p id="footer">Hair Salon © 2020</p>
      </footer>
    </div>
  </body>
</html>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model FavoriteClient.Models.Stylist

<h4>Add a new stylist</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Type)
  @Html.TextBoxFor(model => model.Type)
  <br>
  <input type="submit" value="Add new stylist" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all stylists", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@using FavoriteClient.Models
@model FavoriteClient.Models.Stylist

<h2>Stylist Details</h2>
<hr>
<h4>Clients:</h4>
@foreach (Client client in @Model.Clients)
{
  <li> @client.Name </li>
}
<br> 
<p>@Html.ActionLink("Home", "Index", "Home")</p>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using FavoriteClient.Models;
@model List<FavoriteClient.Models.Stylist>;

<h1>Stylists</h1>

@if (@Model.Count == 0)
{
  <h3>No stylists have been added yet! Please add a stylist.</h3> 
  <p>@Html.ActionLink("Add new stylist", "Create")</p>
  <p>@Html.ActionLink("Home", "Index", "Home")</p>
}
else
{
@foreach (Stylist stylist in Model)
{
  <li>@Html.ActionLink($"{stylist.Type}", "Details", new { id = stylist.StylistId })</li>
}
<br>
<p>@Html.ActionLink("Add new stylist", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>
}










  
    
  